// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed app-icon.png
var resourceIconPngData []byte
var resourceIconPng = &fyne.StaticResource{
	StaticName:    "./app-icon.png",
	StaticContent: resourceIconPngData,
}

//go:embed game-icon.png
var resourceGameIconPngData []byte
var resourceGameIconPng = &fyne.StaticResource{
	StaticName:    "./game-icon.png",
	StaticContent: resourceGameIconPngData,
}
